---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - power.intel.com
  resources:
  - cstates
  - powerconfigs
  - powernodes
  - powerpods
  - powerprofiles
  - powerworkloads
  - timeofdays
  - uncores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.intel.com
  resources:
  - cstates/status
  - powerconfigs/status
  - powernodes/status
  - powerpods/status
  - powerprofiles/status
  - powerworkloads/status
  - timeofdays/status
  - uncores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - power.intel.com
  resources:
  - uncores/finalizers
  verbs:
  - update
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
