---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  name: powernodes.power.intel.com
spec:
  group: power.intel.com
  names:
    kind: PowerNode
    listKind: PowerNodeList
    plural: powernodes
    singular: powernode
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: PowerNode is the Schema for the powernodes API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: PowerNodeSpec defines the desired state of PowerNode
            type: object
          status:
            description: PowerNodeStatus defines the observed state of PowerNode
            properties:
              customDevices:
                description: The CustomDevices include alternative devices that represent
                  other resources
                items:
                  type: string
                type: array
              powerContainers:
                description: Information about the containers in the cluster utilizing
                  some PowerWorkload
                items:
                  properties:
                    exclusiveCpus:
                      description: The exclusive CPUs given to this Container
                      items:
                        type: integer
                      type: array
                    id:
                      description: The ID of the Container
                      type: string
                    name:
                      description: The name of the Container
                      type: string
                    pod:
                      description: The name of the Pod the Container is running on
                      type: string
                    powerProfile:
                      description: The PowerProfile that the Container is utilizing
                      type: string
                    workload:
                      description: The PowerWorkload that the Container is utilizing
                      type: string
                  type: object
                type: array
              powerProfiles:
                description: The power profiles available on this node with their
                  settings
                items:
                  type: string
                type: array
              powerWorkloads:
                description: The power workloads currently configured on this node
                items:
                  type: string
                type: array
              reservedPools:
                description: Reserved pools with their configurations
                items:
                  type: string
                type: array
              sharedPool:
                description: The shared pool configuration and cores
                type: string
              unaffectedCores:
                description: Cores are not affected by any Power Profiles
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
